[package]
name = "zcash_voting-zakura"
version = "3.1.0-rc.12"
edition = "2021"
rust-version = "1.88"
description = "Zakura wallet-libraries backend for Zcash shielded voting."
license = "MIT OR Apache-2.0"
repository = "https://github.com/valargroup/zcash_voting"
readme = "README.md"

[features]
test-fixtures = ["zcash-voting-impl/test-fixtures"]

[dependencies]
zcash-voting-impl = { path = "../zcash-voting-impl", version = "=3.1.0-rc.12", default-features = false, features = ["zakura"] }
